#!/usr/bin/env python3
"""Write, and re-assert, which implementations produced `identity_nlst_full_n2231.csv`.

The table was generated before the driver recorded its callees, so these facts are reconstructed
rather than captured. That is a weaker claim and the sidecar says so in its own text. What makes
the reconstruction checkable rather than asserted is one temporal fact this script verifies every
time it runs: **the last commit touching either comparator predates the first row's timestamp**,
so the source in the tree is the source that ran. If someone edits a comparator, the argument
stops holding and this exits non-zero rather than quietly printing a stale digest.

It cannot close the gap entirely, and nothing run afterwards can -- that is the same limit M3a
states about reproducing a published score. Runs from version 1.1.0 of the driver carry the
`ours_callee_*` / `ref_callee_*` columns and need no reconstruction.

Run: python3 scripts/record_callee_provenance.py [--write]
"""
from __future__ import annotations

import csv
import datetime as dt
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
from callee_provenance import callee_record  # noqa: E402
from agatston_vectorised import agatston_vectorised  # noqa: E402
from agatston_vendor_ref import agatston_naive  # noqa: E402

TABLE = REPO / "results_expected" / "identity_nlst_full_n2231.csv"
SIDECAR = REPO / "results_expected" / "identity_nlst_full_n2231.provenance.md"
ARMS = [("CAC Plus, vectorised", agatston_vectorised, "src/agatston_vectorised.py"),
        ("reference comparator", agatston_naive, "src/agatston_vendor_ref.py")]


def last_commit(rel: str) -> tuple[str, dt.datetime]:
    """The commit that last touched this file, not the repository HEAD.

    `callee_record` reports HEAD, which is the right thing for a run -- it pins the whole tree
    alongside the dirty flag. It is the wrong thing here: this sidecar is a statement about two
    files, and HEAD moves for reasons that have nothing to do with either of them.
    """
    out = subprocess.run(["git", "-C", str(REPO), "log", "-1", "--format=%H %cI", "--", rel],
                         capture_output=True, text=True, timeout=15)
    sha, iso = out.stdout.strip().split()
    return sha, dt.datetime.fromisoformat(iso).replace(tzinfo=None)


def main() -> int:
    with TABLE.open(newline="", encoding="utf-8") as fh:
        dates = sorted(r["processing_date"] for r in csv.DictReader(fh) if r["processing_date"])
    run_start = dt.datetime.strptime(dates[0], "%Y-%m-%d %H:%M:%S")

    lines, bad = [], []
    for label, fn, rel in ARMS:
        rec = callee_record(fn)
        sha, changed = last_commit(rel)
        if changed >= run_start:
            bad.append(f"{rel} last changed {changed:%Y-%m-%d %H:%M} at or after the run "
                       f"began {run_start:%Y-%m-%d %H:%M} -- the tree is no longer the run")
        if rec["callee_repo_dirty"] == "yes":
            bad.append(f"{rel} has uncommitted changes; its digest describes no commit")
        lines.append((label, rel, rec, sha, changed))

    print(f"table rows span {dates[0]} .. {dates[-1]}")
    for label, rel, rec, _sha, changed in lines:
        print(f"  {label:<22} {rel}  last changed {changed:%Y-%m-%d}  "
              f"sha256 {rec['callee_source_sha256'][:16]}")
    if bad:
        print("\nFAIL:\n  " + "\n  ".join(bad))
        return 1

    body = [
        "# Which implementations produced `identity_nlst_full_n2231.csv`",
        "",
        "Generated by `scripts/record_callee_provenance.py`; do not edit by hand.",
        "",
        "**This is reconstructed, not captured.** The run predates version 1.1.0 of the driver,",
        "which records its callees in the table itself. What supports the reconstruction is a",
        "fact the generator re-checks on every run: the last commit touching either file below",
        f"predates the first row's timestamp ({dates[0]}), and neither worktree is dirty, so the",
        "source in the tree is the source that ran. A later edit makes the generator fail rather",
        "than print a stale digest.",
        "",
        "It remains the weaker form of the claim. Digests taken at run time are the stronger one,",
        "and after a run there is no way back to it.",
        "",
        "| Arm | Module | Function | Source SHA-256 | Commit that last touched it | Date |",
        "|---|---|---|---|---|---|",
    ]
    for label, rel, rec, sha, changed in lines:
        body.append(f"| {label} | `{rel}` | `{rec['callee_qualname'].split('.')[-1]}` | "
                    f"`{rec['callee_source_sha256'][:32]}…` | `{sha[:12]}` | "
                    f"{changed:%Y-%m-%d} |")
    body += [
        "",
        f"Rows span `{dates[0]}` to `{dates[-1]}`; driver `run_full_identity.py` version 1.0.0,",
        "in `ai-cac-research/results/c1_full_cohort_identity_20260920/`.",
        "",
        "**The reference comparator is our transcription of the vendor's logic, not the vendor's",
        "code** — its own docstring says so, and Online Methods M15 states it. The synthetic arm",
        "of the same comparison ran against the vendor's published implementation. Repeating this",
        "arm against the pinned upstream function is a separate, planned run.",
        "",
    ]
    if "--write" in sys.argv:
        SIDECAR.write_text("\n".join(body), encoding="utf-8")
        print(f"\nwritten: {SIDECAR.relative_to(REPO)}")
    else:
        print("\nPASS: the reconstruction holds. Pass --write to refresh the sidecar.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
